# Standard Project Ignis English locale file, copyright (C) 2020
#!system for system strings
#!victory for victory reasons
#!counter for counter names
#!setname for archetype names

#Custom Archetype
!setname 0x9554 Recruit
!setname 0x9b55 Infested
!setname 0x9c56 Elite
!setname 0x9d57 Spartan