Duel.LoadScript("MeubleConstant.lua")

--Installation 04
local s,id=GetID()
function s.initial_effect(c)
    local e0=Effect.CreateEffect(c)
	e0:SetType(EFFECT_TYPE_ACTIVATE)
	e0:SetCode(EVENT_FREE_CHAIN)
	c:RegisterEffect(e0)
    local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetCategory(CATEGORY_TOHAND+CATEGORY_SEARCH+CATEGORY_HANDES)
	e1:SetType(EFFECT_TYPE_IGNITION)
	e1:SetRange(LOCATION_FZONE)
	e1:SetCountLimit(1,{id,1})
	e1:SetTarget(s.thtg)
	e1:SetOperation(s.thop)
	c:RegisterEffect(e1)
    local e2=Effect.CreateEffect(c)
    e2:SetProperty(EFFECT_FLAG_CLIENT_HINT)
    e2:SetDescription(aux.Stringid(id,1))
	e2:SetType(EFFECT_TYPE_FIELD)
	e2:SetRange(LOCATION_FZONE)
	e2:SetTargetRange(LOCATION_MZONE,0)
    e2:SetCode(EFFECT_CHANGE_CODE)
    e2:SetTarget(s.target)
	e2:SetValue(CARD_INFESTED_RECRUITS)
	c:RegisterEffect(e2)
    local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD)
	e3:SetCode(EFFECT_ADD_TYPE)
	e3:SetRange(LOCATION_FZONE)
	e3:SetTargetRange(LOCATION_MZONE,0)
    e3:SetCondition(s.chgcon)
	e3:SetTarget(s.target)
	e3:SetValue(TYPE_EFFECT)
	c:RegisterEffect(e3)
    local e4=Effect.CreateEffect(c)
    e4:SetDescription(aux.Stringid(id,2))
	e4:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e4:SetType(EFFECT_TYPE_QUICK_O)
    e4:SetProperty(EFFECT_FLAG_DELAY+EFFECT_FLAG_CARD_TARGET+EFFECT_FLAG_CANNOT_INACTIVATE+EFFECT_FLAG_CANNOT_DISABLE)
    e4:SetCode(EVENT_FREE_CHAIN)
    e4:SetRange(LOCATION_MZONE)
	e4:SetCountLimit(2,{CARD_INFESTED_RECRUITS,2})
	e4:SetCost(Cost.SelfToGrave)
	e4:SetTarget(s.spstg)
	e4:SetOperation(s.spsop)
    e4:SetHintTiming(0,TIMING_STANDBY_PHASE|TIMING_MAIN_END|TIMINGS_CHECK_MONSTER_E)
    local e5=Effect.CreateEffect(c)
	e5:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
	e5:SetRange(LOCATION_FZONE)
	e5:SetTargetRange(LOCATION_MZONE,0)
    e5:SetCondition(s.chgcon)
    e5:SetTarget(s.target)
    e5:SetLabelObject(e4)
	c:RegisterEffect(e5)
    local e6a=Effect.CreateEffect(c)
    e6a:SetType(EFFECT_TYPE_SINGLE)
    e6a:SetProperty(EFFECT_FLAG_CLIENT_HINT)
    e6a:SetDescription(aux.Stringid(id,1))
    local e6b=Effect.CreateEffect(c)
    e6b:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_GRANT)
    e6b:SetRange(LOCATION_FZONE)
    e6b:SetTargetRange(LOCATION_MZONE,0)
    e6b:SetTarget(s.target)
    e6b:SetLabelObject(e6a)
    c:RegisterEffect(e6b)
end
s.listed_names={CARD_INFESTED_RECRUITS}
function s.thfilter(c)
	return c:IsSetCard(SET_RECRUIT) and c:IsAbleToHand()
end
function s.mcfilter(c,tp)
    return c:IsFaceup() and c:IsOwner(1-tp) and not c:IsCode(955000010)
end
function s.spsfilter(c,e,tp)
    return c:IsCanBeSpecialSummoned(e,0,tp,false,false)
end
function s.thtg(e,tp,eg,ep,ev,re,r,rp,chk)
	if chk==0 then return Duel.IsExistingMatchingCard(s.thfilter,tp,LOCATION_DECK,0,1,nil) end
	Duel.SetOperationInfo(0,CATEGORY_TOHAND,nil,1,tp,LOCATION_DECK)
	Duel.SetOperationInfo(0,CATEGORY_HANDES,nil,1,tp,1)
end
function s.thop(e,tp,eg,ep,ev,re,r,rp)
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_ATOHAND)
	local g=Duel.SelectMatchingCard(tp,s.thfilter,tp,LOCATION_DECK,0,1,1,nil)
	if #g>0 and Duel.SendtoHand(g,nil,REASON_EFFECT)>0 then
		Duel.ConfirmCards(1-tp,g)
		Duel.ShuffleHand(tp)
		Duel.BreakEffect()
		Duel.DiscardHand(tp,nil,1,1,REASON_EFFECT|REASON_DISCARD,nil)
	end
end
function s.chgcon(e,c)
    return Duel.GetTurnPlayer()~=e:GetHandlerPlayer()
end
function s.target(e,c)
    local tp=c:GetControler()
	return c:IsFaceup() and c:IsOwner(1-tp)
end
function s.spstg(e,tp,eg,ep,ev,re,r,rp,chk,chkc)
	if chkc then return chkc:IsLocation(LOCATION_GRAVE) and s.spsfilter(chkc,e,tp) end
	if chk==0 then return Duel.GetLocationCount(tp,LOCATION_MZONE)>0 
		and Duel.IsExistingTarget(s.spsfilter,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,nil,e,tp) end
	Duel.Hint(HINT_SELECTMSG,tp,HINTMSG_SPSUMMON)
	local g=Duel.SelectTarget(tp,s.spsfilter,tp,LOCATION_GRAVE,LOCATION_GRAVE,1,1,nil,e,tp)
	Duel.SetOperationInfo(0,CATEGORY_SPECIAL_SUMMON,g,1,0,0)
end
function s.spsop(e,tp,eg,ep,ev,re,r,rp)
    local tc=Duel.GetFirstTarget()
    local c=e:GetHandler()
	if tc:IsRelateToEffect(e) and Duel.SpecialSummonStep(tc,0,tp,tp,false,false,POS_FACEUP) then
        tc:NegateEffects(c)
	end
	Duel.SpecialSummonComplete()
end
function s.namefilter(c,tp)
	return c:IsFaceup() and c:IsOwner(1-tp)
end